CREATE TABLE "bases" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "tables" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"base_id" INTEGER NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "fields" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"table_id" INTEGER NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"type" VARCHAR(255) NOT NULL DEFAULT 'char',
	"position" INTEGER NOT NULL,
	"description" TEXT,
	"options" JSONB,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "records" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"table_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"position" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "cells" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"field_id" INTEGER NOT NULL,
	"record_id" INTEGER NOT NULL,
	"value" JSONB,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "field_select_options" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"field_id" INTEGER NOT NULL,
	"label" VARCHAR(255) NOT NULL,
	"color" VARCHAR(255) NOT NULL,
	"position" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "record_relations" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"field_id" INTEGER,
	"source_record_id" INTEGER NOT NULL,
	"target_record_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

ALTER TABLE "fields"
ADD FOREIGN KEY("table_id") REFERENCES "tables"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "records"
ADD FOREIGN KEY("table_id") REFERENCES "tables"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "cells"
ADD FOREIGN KEY("record_id") REFERENCES "records"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "cells"
ADD FOREIGN KEY("field_id") REFERENCES "fields"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "tables"
ADD FOREIGN KEY("base_id") REFERENCES "bases"("id")
ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE "field_select_options"
ADD FOREIGN KEY("field_id") REFERENCES "fields"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "record_relations"
ADD FOREIGN KEY("source_record_id") REFERENCES "records"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "record_relations"
ADD FOREIGN KEY("target_record_id") REFERENCES "records"("table_id")
ON UPDATE SET NULL ON DELETE CASCADE;
ALTER TABLE "record_relations"
ADD FOREIGN KEY("field_id") REFERENCES "fields"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TYPE field_type AS ENUM (
  'text',
  'number',
  'checkbox',
  'date',
  'single_select',
  'multi_select',
  'many2one',
  'one2many',
  'many2many',
  'formula'
);

ALTER TABLE fields
ALTER COLUMN type TYPE field_type USING type::field_type;